const books = [
    {
      name: "To Kill a Mockingbird",
      authorFirst: "Harper",
      authorLast: "Lee",
      publishDate: 1960,
      genre: ["mystery", "historical", "fiction"],
    },
    {
      name: "The Great Gatsby",
      authorFirst: "F. Scott",
      authorLast: "Fitzgerald",
      publishDate: 1925,
      genre: ["mystery", "historical", "fiction"],
    },
    {
      name: "The Hobbit",
      authorFirst: "JRR",
      authorLast: "Tolkien",
      publishDate: 1937,
      genre: ["fantasy", "fiction"],
    },
    {
      name: "Harry Potter and the Deathly Hallows",
      authorFirst: "JK",
      authorLast: "Rowling",
      publishDate: 1997,
      genre: ["fantasy", , "fiction"],
    },
    {
      name: "Ulysses",
      authorFirst: "James",
      authorLast: "Joyce",
      publishDate: 1918,
      genre: ["historical", "non-fiction"],
    },
    {
      name: "War and Peace",
      authorFirst: "Leo",
      authorLast: "Tolstoy",
      publishDate: 1867,
      genre: ["historical", "fiction"],
    },
    {
      name: "Pride and Prejudice",
      authorFirst: "Jane",
      authorLast: "Austen",
      publishDate: 1813,
      genre: ["fiction"],
    },
    {
      name: "The Catcher in the Rye",
      authorFirst: "JD",
      authorLast: "Salinger",
      publishDate: 1951,
      genre: ["fiction"],
    },
    {
      name: "Great Expectations",
      authorFirst: "Charles",
      authorLast: "Dickens",
      publishDate: 1861,
      genre: ["historical", "fiction"],
    },
    {
      name: "Little Women",
      authorFirst: "Lousia May",
      authorLast: "Alcott",
      publishDate: 1868,
      genre: ["womens", "historical", "fiction"],
    },
    {
        name: "Farenheit 451",
        authorFirst: "Ray",
        authorLast: "Bradbury",
        publishDate: 1953,
        genre: ["dystopian", "fiction"],
    },
    {
      name: "1984",
      authorFirst: "George",
      authorLast: "Orwell",
      publishDate: 1949,
      genre: ["dystopian", "fiction"],
    },
    {
      name: "The Lord of the Rings",
      authorFirst: "JRR",
      authorLast: "Tolkien",
      publishDate: 1954,
      genre: ["fantasy", "fiction"],
    },
    {
      name: "Brave New World",
      authorFirst: "Aldous",
      authorLast: "Huxley",
      publishDate: 1932,
      genre: ["dystopian", "fiction"],
    },
    {
      name: "The Chronicles of Narnia",
      authorFirst: "CS",
      authorLast: "Lewis",
      publishDate: 1950,
      genre: ["fantasy", "fiction"],
    },
    {
      name: "Moby-Dick",
      authorFirst: "Herman",
      authorLast: "Melville",
      publishDate: 1851,
      genre: ["adventure", "fiction"],
    },
    {
      name: "The Odyssey",
      authorFirst: "Homer",
      authorLast: "",
      publishDate: -800,
      genre: ["epic", "poetry"],
    },
    {
      name: "One Hundred Years of Solitude",
      authorFirst: "Gabriel",
      authorLast: "García Márquez",
      publishDate: 1967,
      genre: ["magical realism", "fiction"],
    },
    {
      name: "The Road",
      authorFirst: "Cormac",
      authorLast: "McCarthy",
      publishDate: 2006,
      genre: ["post-apocalyptic", "fiction"],
    },
    {
      name: "The Hitchhiker's Guide to the Galaxy",
      authorFirst: "Douglas",
      authorLast: "Adams",
      publishDate: 1979,
      genre: ["science fiction", "humor"],
    },
    {
      name: "Crime and Punishment",
      authorFirst: "Fyodor",
      authorLast: "Dostoevsky",
      publishDate: 1866,
      genre: ["psychological thriller", "fiction"],
    },
    {
      name: "The Picture of Dorian Gray",
      authorFirst: "Oscar",
      authorLast: "Wilde",
      publishDate: 1890,
      genre: ["gothic", "fiction"],
    },
    {
      name: "The Shining",
      authorFirst: "Stephen",
      authorLast: "King",
      publishDate: 1977,
      genre: ["horror", "fiction"],
    },
    {
      name: "The Grapes of Wrath",
      authorFirst: "John",
      authorLast: "Steinbeck",
      publishDate: 1939,
      genre: ["historical", "fiction"],
    },
    {
      name: "Slaughterhouse-Five",
      authorFirst: "Kurt",
      authorLast: "Vonnegut",
      publishDate: 1969,
      genre: ["science fiction", "satire"],
    },
    {
      name: "The Scarlet Letter",
      authorFirst: "Nathaniel",
      authorLast: "Hawthorne",
      publishDate: 1850,
      genre: ["historical", "fiction"],
    },
    {
      name: "The Brothers Karamazov",
      authorFirst: "Fyodor",
      authorLast: "Dostoevsky",
      publishDate: 1880,
      genre: ["philosophical", "fiction"],
    },
    {
      name: "Anna Karenina",
      authorFirst: "Leo",
      authorLast: "Tolstoy",
      publishDate: 1877,
      genre: ["historical", "fiction"],
    },
    {
      name: "The Martian",
      authorFirst: "Andy",
      authorLast: "Weir",
      publishDate: 2011,
      genre: ["science fiction", "adventure"],
    },
    {
      name: "The Count of Monte Cristo",
      authorFirst: "Alexandre",
      authorLast: "Dumas",
      publishDate: 1844,
      genre: ["adventure", "historical", "fiction"],
    },
    {
      name: "The Stand",
      authorFirst: "Stephen",
      authorLast: "King",
      publishDate: 1978,
      genre: ["post-apocalyptic", "horror"],
    },
    {
      name: "A Tale of Two Cities",
      authorFirst: "Charles",
      authorLast: "Dickens",
      publishDate: 1859,
      genre: ["historical", "fiction"],
    },
    {
      name: "The Alchemist",
      authorFirst: "Paulo",
      authorLast: "Coelho",
      publishDate: 1988,
      genre: ["philosophical", "fiction"],
    },
    {
      name: "Frankenstein",
      authorFirst: "Mary",
      authorLast: "Shelley",
      publishDate: 1818,
      genre: ["gothic", "science fiction"],
    },
    {
      name: "Dune",
      authorFirst: "Frank",
      authorLast: "Herbert",
      publishDate: 1965,
      genre: ["science fiction"],
    },
    {
      name: "The Girl with the Dragon Tattoo",
      authorFirst: "Stieg",
      authorLast: "Larsson",
      publishDate: 2005,
      genre: ["mystery", "thriller"],
    },
  ];
  
  