const books = [
    {
      name: "To Kill a Mockingbird",
      authorFirst: "Harper",
      authorLast: "Lee",
      publishDate: 1960,
      genre: ["mystery", "historical", "fiction"],
    },
    {
      name: "The Great Gatsby",
      authorFirst: "F. Scott",
      authorLast: "Fitzgerald",
      publishDate: 1925,
      genre: ["mystery", "historical", "fiction"],
    },
    {
      name: "The Hobbit",
      authorFirst: "JRR",
      authorLast: "Tolkien",
      publishDate: 1937,
      genre: ["fantasy", "fiction"],
    },
    {
      name: "Harry Potter and the Deathly Hallows",
      authorFirst: "JK",
      authorLast: "Rowling",
      publishDate: 1997,
      genre: ["fantasy", , "fiction"],
    },
    {
      name: "Ulysses",
      authorFirst: "James",
      authorLast: "Joyce",
      publishDate: 1918,
      genre: ["historical", "non-fiction"],
    },
    {
      name: "War and Peace",
      authorFirst: "Leo",
      authorLast: "Tolstoy",
      publishDate: 1867,
      genre: ["historical", "fiction"],
    },
    {
      name: "Pride and Prejudice",
      authorFirst: "Jane",
      authorLast: "Austen",
      publishDate: 1813,
      genre: ["fiction"],
    },
    {
      name: "The Catcher in the Rye",
      authorFirst: "JD",
      authorLast: "Salinger",
      publishDate: 1951,
      genre: ["fiction"],
    },
    {
      name: "Great Expectations",
      authorFirst: "Charles",
      authorLast: "Dickens",
      publishDate: 1861,
      genre: ["historical", "fiction"],
    },
    {
      name: "Little Women",
      authorFirst: "Lousia May",
      authorLast: "Alcott",
      publishDate: 1868,
      genre: ["womens", "historical", "fiction"],
    },
    {
        name: "Farenheit 451",
        authorFirst: "Ray",
        authorLast: "Bradbury",
        publishDate: 1953,
        genre: ["dystopian", "fiction"],
    }
  ];
  